# Generated by Django 6.0.4 on 2026-05-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., India vs Australia - 1st T20I', max_length=150)),
                ('match_type', models.CharField(choices=[('T20', 'Twenty20'), ('ODI', 'One Day International'), ('Test', 'Test Match')], default='T20', max_length=10)),
                ('overs_limit', models.IntegerField(default=20, help_text='Total overs per innings')),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('toss_decision', models.CharField(blank=True, choices=[('Bat', 'Bat'), ('Bowl', 'Bowl')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Completed', 'Completed'), ('Abandoned', 'Abandoned')], default='Scheduled', max_length=20)),
                ('result_margin', models.CharField(blank=True, help_text='e.g., IND won by 10 runs', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(help_text='e.g., IND, AUS, ENG', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchInnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_number', models.IntegerField(default=1, help_text='1 or 2')),
                ('total_runs', models.IntegerField(default=0)),
                ('total_wickets', models.IntegerField(default=0)),
                ('total_balls', models.IntegerField(default=0, help_text='Number of legal balls bowled')),
                ('is_completed', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='scorecard.match')),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='scorecard.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_innings', to='scorecard.team')),
            ],
            options={
                'unique_together': {('match', 'innings_number')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder'), ('Wicket-Keeper', 'Wicket-Keeper')], default='Batsman', max_length=30)),
                ('batting_style', models.CharField(choices=[('Right-Hand', 'Right-Hand'), ('Left-Hand', 'Left-Hand')], default='Right-Hand', max_length=30)),
                ('bowling_style', models.CharField(choices=[('Right-Arm Fast', 'Right-Arm Fast'), ('Right-Arm Medium', 'Right-Arm Medium'), ('Right-Arm Spin', 'Right-Arm Spin'), ('Left-Arm Fast', 'Left-Arm Fast'), ('Left-Arm Medium', 'Left-Arm Medium'), ('Left-Arm Spin', 'Left-Arm Spin'), ('None', 'None')], default='None', max_length=30)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='scorecard.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_a', to='scorecard.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_b', to='scorecard.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toss_won_matches', to='scorecard.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='scorecard.team'),
        ),
        migrations.CreateModel(
            name='BowlingScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balls_bowled', models.IntegerField(default=0, help_text='Number of legal balls bowled')),
                ('runs_conceded', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('maidens', models.IntegerField(default=0)),
                ('wides_bowled', models.IntegerField(default=0)),
                ('noballs_bowled', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_cards', to='scorecard.match')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowlers_stats', to='scorecard.matchinnings')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_stats', to='scorecard.player')),
            ],
            options={
                'unique_together': {('innings', 'player')},
            },
        ),
        migrations.CreateModel(
            name='BattingScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('dismissal_status', models.CharField(choices=[('DNB', 'Did Not Bat'), ('Not Out', 'Not Out'), ('Bowled', 'Bowled'), ('Caught', 'Caught'), ('LBW', 'LBW'), ('Run Out', 'Run Out'), ('Stumped', 'Stumped'), ('Retired Hurt', 'Retired Hurt'), ('Hit Wicket', 'Hit Wicket')], default='DNB', max_length=30)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_cards', to='scorecard.match')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batsmen_stats', to='scorecard.matchinnings')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batting_wickets_taken', to='scorecard.player')),
                ('fielder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batting_catches_taken', to='scorecard.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_stats', to='scorecard.player')),
            ],
            options={
                'unique_together': {('innings', 'player')},
            },
        ),
        migrations.CreateModel(
            name='BallByBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.IntegerField(help_text='0-indexed (e.g. 0 for first over, 19 for 20th over)')),
                ('ball_number', models.IntegerField(help_text='1 to 6 (or higher for extra balls like wides/no balls)')),
                ('runs_batsman', models.IntegerField(default=0, help_text='Runs scored off the bat')),
                ('runs_extras', models.IntegerField(default=0, help_text='Extra runs (from wides, no-balls, byes, etc.)')),
                ('extra_type', models.CharField(choices=[('None', 'None'), ('Wide', 'Wide'), ('No Ball', 'No Ball'), ('Leg Bye', 'Leg Bye'), ('Bye', 'Bye')], default='None', max_length=20)),
                ('wicket', models.BooleanField(default=False)),
                ('wicket_type', models.CharField(choices=[('None', 'None'), ('Bowled', 'Bowled'), ('Caught', 'Caught'), ('LBW', 'LBW'), ('Run Out', 'Run Out'), ('Stumped', 'Stumped'), ('Retired Hurt', 'Retired Hurt'), ('Hit Wicket', 'Hit Wicket')], default='None', max_length=20)),
                ('commentary', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='scorecard.matchinnings')),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_deliveries', to='scorecard.player')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_deliveries', to='scorecard.player')),
                ('dismissed_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissals', to='scorecard.player')),
                ('fielder', models.ForeignKey(blank=True, help_text='Fielder who took the catch/stumped/runout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisting_dismissals', to='scorecard.player')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_striker_deliveries', to='scorecard.player')),
            ],
            options={
                'ordering': ['over_number', 'ball_number'],
                'unique_together': {('innings', 'over_number', 'ball_number')},
            },
        ),
    ]
