# Generated by Django 6.0.4 on 2026-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0002_eventregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
