# Generated by Django 6.0.3 on 2026-05-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="status",
        ),
    ]
