# Generated by Django 6.0.3 on 2026-05-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_address_user_cover_letter_user_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("job_creator", "Job Creator"), ("candidate", "Candidate")],
                default="candidate",
                max_length=20,
            ),
        ),
    ]
