# Generated by Django 6.0.3 on 2026-04-26 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("College", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="college",
            new_name="college_id",
        ),
        migrations.RemoveField(
            model_name="college",
            name="id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="id",
        ),
        migrations.AddField(
            model_name="college",
            name="college_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="studentregistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="College.college",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="College.student",
                    ),
                ),
            ],
        ),
    ]
