# Generated by Django 6.0.3 on 2026-04-26 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="event_date",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="location",
            new_name="event_name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="name",
        ),
        migrations.CreateModel(
            name="EventRegistration_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Event.event"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Eventregistration",
        ),
    ]
