# Generated by Django 6.0.4 on 2026-04-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Students", "0002_studentsregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("principal", models.CharField(max_length=100)),
            ],
        ),
    ]
