# Generated by Django 6.0.4 on 2026-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Students", "0003_college"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="college",
            name="principal",
        ),
        migrations.AlterField(
            model_name="college",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="students",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
